cd /d %~dp0
SET BASE_PATH=%~dp0
SET PYTHON_VER=3.8.6
SET DL_PYTHON=python-%PYTHON_VER%-embed-amd64
SET PYTHON_PATH=%BASE_PATH%%DL_PYTHON%

SET PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%



